### ISSUE TITLE
Finetuned model

### ISSUE THREAD

**Issue by yogeshl18** [ChangwenXu98/TransPolymer#2]
Hello, Thank you for the great work.
I am wondering if you have trained model to run inference on. I want to test model for property prediction on test dataset.
I tried training but its super slow to train on my local machine!

**Comment by ChangwenXu98** [comment]
Thanks for your comment. We do have finetuned the model and tested it on test datasets. Usually, it takes several hours for small datasets or one or two days for large ones to finetune the model with 5-fold cross-validation if you have RTX 3090 or better GPUs.

**Comment by yogeshl18** [comment]
Thank you for the quick reply. Is it possible for you to upload the finetuned model here ? 
I want to reproduce the results. 
I have two questions:

1.  Have you finetuned model independently for each different property e.g Eea ? Is it possible to do training for all properties together ?  
2. If I wish to do new property detection, do you think I can finetune this model with new property dataset and it will work well ?

**Comment by ChangwenXu98** [comment]
I'm sorry that we do not include finetuned model checkpoints in the repository because they would take up more than 10 GB for all the downstream tasks we experimented with in this work. To reproduce the results, we strongly suggest that you start with the pretrained model and play with any dataset you're interested in.

With regard to your questions:
1. We finetuned the model independently for each dataset. However, I think it's worth trying to simultaneously make multiple property predictions for polymers. You can refer to the works on multi-task regression.
2. I believe so. The pretrained model should serve as a foundation model so that it can be finetuned to learn domain-specific knowledge.
